---
partition_var_lib_mysql: True
var_lib_mysql_disk: /var/vdc

mariadb_root_password: root

max_connections: 500
connection_timeout: 5
wait_timeout: 60
innodb_buffer_pool_size: 1024
innodb_buffer_pool_instances: 6
innodb_log_buffer_size: 8M
innodb_log_file_size: 24M
innodb_concurrency: 16
innodb_lock_wait_timeout: 120

max_allowed_packet: 128M

innodb_file_format: barracuda
innodb_large_prefix: 1
