elasticsearch_config:
  node_name: node1
  cluster_name: cluster1
  plugin_dir: /usr/share/elasticsearch/plugins
  home_dir: /usr/share/elasticsearch

# by default the kopf ui and hq plugin are installed.
elasticsearch_plugins:
  - { name: 'royrusso/elasticsearch-HQ', shortname: 'hq'}

elasticsearch_heap_size: 2g
elasticsearch_version: 5
