blackfire_server_key: "aa-bb-REPLACE THIS-cc-dd"
blackfire_server_token: "aa-bb-REPLACE THIS-cc-dd"
blackfire_client_key: "aa-bb-REPLACE THIS-cc-dd"
blackfire_client_token: "aa-bb-REPLACE THIS-cc-dd"
enable_blackfire: false

xdebug:
 - section: XDebug
   options:
    - key: xdebug.remote_enable
      val: 1
    - key: xdebug.remote_handler
      val: dbgp
    - key: xdebug.remote_connect_back
      val: 1
    - key: xdebug.remote_port
      val: 9000
    - key: xdebug.remote_autostart
      val: 0

# this can be set to true to add the remote log file.
xdebug_remote_debug_log: false
