# These contain the IP addresses from the admin VPN
firewall_ssh_allowed:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# These servers will do the automatic deployments into the machines
project_additional_ssh_firewall_rules:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# Ensure that these older IP addresses are removed
remove_ssh_firewall_rules:
  #- comment: Admin machine
  #  ip: 10.0.0.1
  #- comment: Test Machine
  #  ip: 127.0.0.1

# These are added after ssh rules
project_additional_firewall_rules:
#- direction: in
#  family: IPv4
#  protocol: tcp
#  source_address_start: 127.0.0.1
#  source_address_end: 127.0.0.255
#  destination_port_start: 22
#  destination_port_end: 22
#  action: accept

upcloud_default_firewall_rules:
  - direction: in
    action: accept
    family: IPv4
    protocol: udp
    source_port_start: 53
    source_port_end: 53
    destination_port_start: 32768
    destination_port_end: 61000
    comment: Allow DNS Responses
  - direction: in
    family: IPv4
    protocol: icmp
    action: accept
    icmp_type: 0
    comment: Allow Ping Responses
  - comment: Allow Sync with NTP servers
    direction: in
    action: accept
    family: IPv4
    protocol: udp
    source_port_start: 123
    source_port_end: 123
    destination_port_start: 123
    destination_port_end: 123
