
varnish:
  port: 8081
  memory: 1G
  acl_internal:
    - ip: 127.0.0.1
  acl_purge:
    - ip: 127.0.0.1
  acl_upstream_proxy:
    - ip: 127.0.0.1
  directors:
    # One app
    - name: test_com_director
      host: test.com
      backends:
        - name: test1_web
          address: 127.0.0.1
          port: 8080

# # Multiple apps
#   - name: test_com_director
#     host: test.com
#     backends:
#       - name: test1_web
#         address: 192.168.1.101
#         port: 8080
#   - name: test2_com_director
#     host: test2.com
#     backends:
#       - name: test2_web
#         address: 192.168.1.102
#         port: 8081
#   - name: test3_com_director
#     host: test3.com
#     backends:
#       - name: test3_web
#         address: 192.168.1.102
#         port: 8081
