---

- include: "fdisk.yml"
  when:
    partition_var_lib_mysql == True

# Setup MariaDB repo

# Mariadb repository
- copy:
    src=mariadb.repo
    dest=/etc/yum.repos.d/mariadb.repo

# Provision our mysql configs
- name: Set my.cnf
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
    owner=root
    mode=0644

- yum:
    name={{ item }}
    state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - xfsprogs
    - MySQL-python

# Create log directory
- file:
    state=directory
    path=/var/log/mysql
    group=mysql
    owner=mysql
    mode=755

- shell:
    systemctl stop mysql

- shell:
    systemctl start mysql

- service: name=mysql state=started enabled=yes

# Update root password

- name: Set root Password
  mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} state=present
  with_items:
    - localhost
  when: change_db_root_password is defined

- name: Add .my.cnf
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: change_db_root_password is defined

- name: Set root Password
  mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} state=present
  with_items:
    - 127.0.0.1
    - ::1
  when: change_db_root_password is defined

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Set open_files_limit override
  template:
    src=override.conf.j2
    dest=/etc/systemd/system/mariadb.service.d/override.conf
    owner=root
    mode=0644
  notify:
    - restart mariadb

- name: Set security/limits.conf limits
  lineinfile:
    dest=/etc/security/limits.conf
    line="mysql    {{ item }}    nofile    {{ innodb_open_files }}"
    regexp="^\*\s+{{ item.limit }}"
    backup=yes
  with_items:
    - soft
    - hard


- shell:
    systemctl daemon-reload
