---

nginx_real_ip: 127.0.0.1

sslterminator_papertrail_follow:
  - /var/log/nginx/ssl-*error.log

sslterminators:
  - server_name: www.test.com
    server_forwards: test.com
    ssl_certificate: /etc/nginx/ssl/wk.dev.pem
    ssl_certificate_key: /etc/nginx/ssl/wk.dev.key
    use_dhparam: True
    backends:
      - 127.0.0.1:8081

httpforwards:
  - server_name: www.test.com
    forwarded_domains: 'test.com www.test.com'

httpsforwards: []

basicauth_enabled: False
basicauth_username: wunder
basicauth_password: wunder123
basicauth_ip:
  - address: 127.0.0.1
  - address: 192.168.0.1

papertrail_enabled: False

# Default distribution CentOS 7
distro: "centos7"

# Browser support for SSL:
# intermediate: Oldest compatible clients: Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7
# modern: Oldest compatible clients: Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and Java 8
ssl_browser_support: "intermediate"
