---

# Setup all of our php-fpm related repositories.

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://dl.iuscommunity.org/pub/ius/stable/Redhat/7/x86_64/ius-release-1.0-14.ius.el7.noarch.rpm"
  when: distro == "rhel7"

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm"
  when: distro == "centos7"

# Mariadb repository for client
- copy:
    src=mariadb/mariadb.repo
    dest=/etc/yum.repos.d/mariadb.repo